# Change these first
owner: hugaf # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: vClaim Bridging Server
    url: https://apijkn.bpjs-kesehatan.go.id/vclaim-rest/referensi/poli/UMU
  - name: Antrean Online BPJS Bridging Server
    url: https://apijkn.bpjs-kesehatan.go.id/antreanrs
  - name: Hugaf
    url: https://hugaf.com
  #- name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
  #  ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Hugaf Monitoring Tools
  introTitle: "**Hugaf** is the monitor and status page."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Hugaf
      href: https://hugaf.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
